version: '3.8'

services:
  db:
    image: postgres
    container_name: base-db-container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
